[workspace]
members = [
  "core",
  "apps/desktop/src-tauri",
  "apps/server",
]
resolver = "2"

[workspace.dependencies]
rspc = { version = "0.1.2" }

[patch.crates-io]
rspc = { git = "https://github.com/oscartbeaumont/rspc", rev = "08c19f5e485dfc6841c7e9877c80058402bf71d7" }